<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CodeIgniter Application Test Suite" tests="4" assertions="3" failures="3" errors="0" time="0.663155">
    <testsuite name="FundooAccountsController_test" file="/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php" tests="4" assertions="3" failures="3" errors="0" time="0.663155">
      <testcase name="testForgotPasswordforgotPassword" class="FundooAccountsController_test" file="/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php" line="16" assertions="0" time="0.086128">
        <system-out>
A PHP Error was encountered

Severity:    Warning
Message:     Invalid argument supplied for foreach()
Filename:    /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
Line Number: 22

Backtrace:
	File: /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
	Line: 22
	Function: _error_handler

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 910
	Function: invokeArgs

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 770
	Function: runTest

	File: /usr/share/php/PHPUnit/Framework/TestResult.php
	Line: 685
	Function: runBare

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 726
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/TestRunner.php
	Line: 429
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 155
	Function: doRun

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 106
	Function: run

	File: /usr/bin/phpunit
	Line: 29
	Function: main


</system-out>
      </testcase>
      <testcase name="testRegistration" class="FundooAccountsController_test" file="/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php" line="30" assertions="1" time="0.267714">
        <failure type="PHPUnit_Framework_ExpectationFailedException">FundooAccountsController_test::testRegistration
Failed asserting that null matches expected '203'.

/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php:47
</failure>
        <system-out>
A PHP Error was encountered

Severity:    Notice
Message:     Undefined index: name
Filename:    /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
Line Number: 39

Backtrace:
	File: /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
	Line: 39
	Function: _error_handler

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 910
	Function: invokeArgs

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 770
	Function: runTest

	File: /usr/share/php/PHPUnit/Framework/TestResult.php
	Line: 685
	Function: runBare

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 726
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/TestRunner.php
	Line: 429
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 155
	Function: doRun

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 106
	Function: run

	File: /usr/bin/phpunit
	Line: 29
	Function: main



A PHP Error was encountered

Severity:    Notice
Message:     Undefined index: number
Filename:    /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
Line Number: 40

Backtrace:
	File: /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
	Line: 40
	Function: _error_handler

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 910
	Function: invokeArgs

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 770
	Function: runTest

	File: /usr/share/php/PHPUnit/Framework/TestResult.php
	Line: 685
	Function: runBare

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 726
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/TestRunner.php
	Line: 429
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 155
	Function: doRun

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 106
	Function: run

	File: /usr/bin/phpunit
	Line: 29
	Function: main



A PHP Error was encountered

Severity:    Notice
Message:     Trying to get property of non-object
Filename:    /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
Line Number: 47

Backtrace:
	File: /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
	Line: 47
	Function: _error_handler

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 910
	Function: invokeArgs

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 770
	Function: runTest

	File: /usr/share/php/PHPUnit/Framework/TestResult.php
	Line: 685
	Function: runBare

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 726
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/TestRunner.php
	Line: 429
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 155
	Function: doRun

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 106
	Function: run

	File: /usr/bin/phpunit
	Line: 29
	Function: main


</system-out>
      </testcase>
      <testcase name="testResetPassword" class="FundooAccountsController_test" file="/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php" line="51" assertions="1" time="0.236624">
        <failure type="PHPUnit_Framework_ExpectationFailedException">FundooAccountsController_test::testResetPassword
Failed asserting that null matches expected '404'.

/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php:65
</failure>
        <system-out>
A PHP Error was encountered

Severity:    Notice
Message:     Trying to get property of non-object
Filename:    /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
Line Number: 65

Backtrace:
	File: /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
	Line: 65
	Function: _error_handler

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 910
	Function: invokeArgs

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 770
	Function: runTest

	File: /usr/share/php/PHPUnit/Framework/TestResult.php
	Line: 685
	Function: runBare

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 726
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/TestRunner.php
	Line: 429
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 155
	Function: doRun

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 106
	Function: run

	File: /usr/bin/phpunit
	Line: 29
	Function: main


</system-out>
      </testcase>
      <testcase name="testLoginValue" class="FundooAccountsController_test" file="/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php" line="68" assertions="1" time="0.072689">
        <failure type="PHPUnit_Framework_ExpectationFailedException">FundooAccountsController_test::testLoginValue
Failed asserting that null matches expected '404'.

/var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php:83
</failure>
        <system-out>
A PHP Error was encountered

Severity:    Notice
Message:     Undefined index: email
Filename:    /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
Line Number: 75

Backtrace:
	File: /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
	Line: 75
	Function: _error_handler

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 910
	Function: invokeArgs

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 770
	Function: runTest

	File: /usr/share/php/PHPUnit/Framework/TestResult.php
	Line: 685
	Function: runBare

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 726
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/TestRunner.php
	Line: 429
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 155
	Function: doRun

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 106
	Function: run

	File: /usr/bin/phpunit
	Line: 29
	Function: main



A PHP Error was encountered

Severity:    Notice
Message:     Undefined property: stdClass::$message
Filename:    /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
Line Number: 83

Backtrace:
	File: /var/www/html/codeigniter/application/tests/controllers/FundooAccountsController_test.php
	Line: 83
	Function: _error_handler

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 910
	Function: invokeArgs

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 770
	Function: runTest

	File: /usr/share/php/PHPUnit/Framework/TestResult.php
	Line: 685
	Function: runBare

	File: /usr/share/php/PHPUnit/Framework/TestCase.php
	Line: 726
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/Framework/TestSuite.php
	Line: 747
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/TestRunner.php
	Line: 429
	Function: run

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 155
	Function: doRun

	File: /usr/share/php/PHPUnit/TextUI/Command.php
	Line: 106
	Function: run

	File: /usr/bin/phpunit
	Line: 29
	Function: main


</system-out>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
